import { Sparkles, X } from 'lucide-react';
import { motion } from 'motion/react';
import Markdown from 'react-markdown';
import type { AIConfig } from '../services/aiService';

interface Props {
  digest: { type: 'daily' | 'weekly'; content: string };
  aiConfig: AIConfig;
  articleCount: number;
  onClose: () => void;
  onExportCSV: () => void;
}

export default function DigestView({ digest, aiConfig, articleCount, onClose, onExportCSV }: Props) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 32 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-white rounded-[40px] border border-[#e5e5e5] shadow-2xl shadow-black/5 overflow-hidden"
    >
      {/* Hero */}
      <div className="relative h-[440px] bg-[#050505] flex flex-col justify-center items-center text-center p-12 overflow-hidden">
        <div className="absolute inset-0 opacity-35">
          <img
            src="https://picsum.photos/seed/editorial/1920/1080?blur=10"
            className="w-full h-full object-cover"
            alt=""
            referrerPolicy="no-referrer"
          />
          <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[#050505]/60 to-[#050505]" />
        </div>
        <div className="relative z-20 max-w-2xl space-y-6">
          <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="flex flex-col items-center gap-3">
            <span className="px-3 py-1 bg-indigo-500/20 backdrop-blur-md border border-indigo-500/30 text-indigo-400 text-[10px] font-bold uppercase tracking-[0.25em] rounded-full">
              AI Intelligence Report
            </span>
            <span className="text-white/40 text-xs font-medium uppercase tracking-[0.35em]">
              {new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}
            </span>
          </motion.div>
          <h1 className="font-heading text-[80px] md:text-[100px] font-bold text-white tracking-tighter leading-[0.85] uppercase italic">
            The<br />Digest
          </h1>
          <p className="text-white/55 text-base font-medium max-w-sm mx-auto leading-relaxed">
            A synthesized overview of the most important developments across your subscriptions.
          </p>
        </div>
        <button
          onClick={onClose}
          className="absolute top-10 right-10 w-11 h-11 bg-white/8 hover:bg-white/15 backdrop-blur-xl rounded-full flex items-center justify-center text-white/70 hover:text-white transition-all border border-white/10 cursor-pointer"
          title="Close digest"
        >
          <X className="w-4.5 h-4.5" />
        </button>
      </div>

      {/* Body */}
      <div className="px-10 py-14 md:px-20 md:py-20 bg-white">
        <div className="max-w-3xl mx-auto">
          <div className="prose prose-neutral prose-lg max-w-none
            prose-headings:font-heading prose-headings:font-bold prose-headings:tracking-tight
            prose-p:text-[#404040] prose-p:leading-[1.8]
            prose-strong:text-indigo-600 prose-strong:font-bold
            prose-li:text-[#525252] prose-li:leading-relaxed
            prose-hr:border-[#e5e5e5]"
          >
            <Markdown>{digest.content}</Markdown>
          </div>

          <div className="mt-16 pt-10 border-t border-[#e5e5e5] flex flex-col sm:flex-row items-center justify-between gap-6">
            <div className="flex items-center gap-4">
              <div className="w-11 h-11 bg-indigo-50 rounded-xl flex items-center justify-center">
                <Sparkles className="w-5 h-5 text-indigo-600" />
              </div>
              <div>
                <p className="text-sm font-semibold text-[#171717]">
                  Generated by {aiConfig.provider.charAt(0).toUpperCase() + aiConfig.provider.slice(1)} AI
                </p>
                <p className="text-xs text-[#a3a3a3] mt-0.5">Based on {articleCount} recent articles</p>
              </div>
            </div>
            <button
              onClick={onExportCSV}
              className="px-6 py-2.5 bg-indigo-600 text-white hover:bg-indigo-700 rounded-xl text-sm font-semibold transition-all shadow-lg shadow-indigo-500/20 cursor-pointer"
            >
              Export data
            </button>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
