export const INITIAL_FEEDS = [
  {
    name: "simonwillison.net",
    xmlUrl: "https://simonwillison.net/atom/everything/",
    htmlUrl: "https://simonwillison.net",
    category: "Engineering",
  },
  {
    name: "jeffgeerling.com",
    xmlUrl: "https://www.jeffgeerling.com/blog.xml",
    htmlUrl: "https://jeffgeerling.com",
    category: "Hardware",
  },
  {
    name: "seangoedecke.com",
    xmlUrl: "https://www.seangoedecke.com/rss.xml",
    htmlUrl: "https://seangoedecke.com",
    category: "Engineering",
  },
  {
    name: "krebsonsecurity.com",
    xmlUrl: "https://krebsonsecurity.com/feed/",
    htmlUrl: "https://krebsonsecurity.com",
    category: "Security",
  },
  {
    name: "daringfireball.net",
    xmlUrl: "https://daringfireball.net/feeds/main",
    htmlUrl: "https://daringfireball.net",
    category: "Tech",
  },
  {
    name: "ericmigi.com",
    xmlUrl: "https://ericmigi.com/rss.xml",
    htmlUrl: "https://ericmigi.com",
    category: "Personal",
  },
  {
    name: "antirez.com",
    xmlUrl: "http://antirez.com/rss",
    htmlUrl: "http://antirez.com",
    category: "Engineering",
  },
  {
    name: "idiallo.com",
    xmlUrl: "https://idiallo.com/feed.rss",
    htmlUrl: "https://idiallo.com",
    category: "Engineering",
  },
  {
    name: "maurycyz.com",
    xmlUrl: "https://maurycyz.com/index.xml",
    htmlUrl: "https://maurycyz.com",
    category: "Engineering",
  },
  {
    name: "pluralistic.net",
    xmlUrl: "https://pluralistic.net/feed/",
    htmlUrl: "https://pluralistic.net",
    category: "Culture",
  },
  {
    name: "shkspr.mobi",
    xmlUrl: "https://shkspr.mobi/blog/feed/",
    htmlUrl: "https://shkspr.mobi",
    category: "Tech",
  },
  {
    name: "lcamtuf.substack.com",
    xmlUrl: "https://lcamtuf.substack.com/feed",
    htmlUrl: "https://lcamtuf.substack.com",
    category: "Security",
  },
  {
    name: "mitchellh.com",
    xmlUrl: "https://mitchellh.com/feed.xml",
    htmlUrl: "https://mitchellh.com",
    category: "Engineering",
  },
  {
    name: "dynomight.net",
    xmlUrl: "https://dynomight.net/feed.xml",
    htmlUrl: "https://dynomight.net",
    category: "Science",
  },
  {
    name: "utcc.utoronto.ca/~cks",
    xmlUrl: "https://utcc.utoronto.ca/~cks/space/blog/?atom",
    htmlUrl: "https://utcc.utoronto.ca/~cks",
    category: "Engineering",
  },
  {
    name: "xeiaso.net",
    xmlUrl: "https://xeiaso.net/blog.rss",
    htmlUrl: "https://xeiaso.net",
    category: "Engineering",
  },
  {
    name: "devblogs.microsoft.com/oldnewthing",
    xmlUrl: "https://devblogs.microsoft.com/oldnewthing/feed",
    htmlUrl: "https://devblogs.microsoft.com/oldnewthing",
    category: "Engineering",
  },
  {
    name: "righto.com",
    xmlUrl: "https://www.righto.com/feeds/posts/default",
    htmlUrl: "https://righto.com",
    category: "Hardware",
  },
  {
    name: "lucumr.pocoo.org",
    xmlUrl: "https://lucumr.pocoo.org/feed.atom",
    htmlUrl: "https://lucumr.pocoo.org",
    category: "Engineering",
  },
  {
    name: "skyfall.dev",
    xmlUrl: "https://skyfall.dev/rss.xml",
    htmlUrl: "https://skyfall.dev",
    category: "Engineering",
  },
  {
    name: "garymarcus.substack.com",
    xmlUrl: "https://garymarcus.substack.com/feed",
    htmlUrl: "https://garymarcus.substack.com",
    category: "AI",
  },
  {
    name: "rachelbythebay.com",
    xmlUrl: "https://rachelbythebay.com/w/atom.xml",
    htmlUrl: "https://rachelbythebay.com",
    category: "Engineering",
  },
  {
    name: "overreacted.io",
    xmlUrl: "https://overreacted.io/rss.xml",
    htmlUrl: "https://overreacted.io",
    category: "Engineering",
  },
  {
    name: "timsh.org",
    xmlUrl: "https://timsh.org/rss/",
    htmlUrl: "https://timsh.org",
    category: "Personal",
  },
  {
    name: "johndcook.com",
    xmlUrl: "https://www.johndcook.com/blog/feed/",
    htmlUrl: "https://johndcook.com",
    category: "Science",
  },
  {
    name: "gilesthomas.com",
    xmlUrl: "https://gilesthomas.com/feed/rss.xml",
    htmlUrl: "https://gilesthomas.com",
    category: "Engineering",
  },
  {
    name: "matklad.github.io",
    xmlUrl: "https://matklad.github.io/feed.xml",
    htmlUrl: "https://matklad.github.io",
    category: "Engineering",
  },
  {
    name: "derekthompson.org",
    xmlUrl: "https://www.theatlantic.com/feed/author/derek-thompson/",
    htmlUrl: "https://derekthompson.org",
    category: "Culture",
  },
  {
    name: "evanhahn.com",
    xmlUrl: "https://evanhahn.com/feed.xml",
    htmlUrl: "https://evanhahn.com",
    category: "Personal",
  },
  {
    name: "terriblesoftware.org",
    xmlUrl: "https://terriblesoftware.org/feed/",
    htmlUrl: "https://terriblesoftware.org",
    category: "Engineering",
  },
  {
    name: "rakhim.exotext.com",
    xmlUrl: "https://rakhim.exotext.com/rss.xml",
    htmlUrl: "https://rakhim.exotext.com",
    category: "Personal",
  },
  {
    name: "joanwestenberg.com",
    xmlUrl: "https://joanwestenberg.com/rss",
    htmlUrl: "https://joanwestenberg.com",
    category: "Culture",
  },
  {
    name: "xania.org",
    xmlUrl: "https://xania.org/feed",
    htmlUrl: "https://xania.org",
    category: "Engineering",
  },
  {
    name: "micahflee.com",
    xmlUrl: "https://micahflee.com/feed/",
    htmlUrl: "https://micahflee.com",
    category: "Security",
  },
  {
    name: "nesbitt.io",
    xmlUrl: "https://nesbitt.io/feed.xml",
    htmlUrl: "https://nesbitt.io",
    category: "Engineering",
  },
  {
    name: "construction-physics.com",
    xmlUrl: "https://www.construction-physics.com/feed",
    htmlUrl: "https://construction-physics.com",
    category: "Science",
  },
  {
    name: "tedium.co",
    xmlUrl: "https://feed.tedium.co/",
    htmlUrl: "https://tedium.co",
    category: "Culture",
  },
  {
    name: "susam.net",
    xmlUrl: "https://susam.net/feed.xml",
    htmlUrl: "https://susam.net",
    category: "Engineering",
  },
  {
    name: "entropicthoughts.com",
    xmlUrl: "https://entropicthoughts.com/feed.xml",
    htmlUrl: "https://entropicthoughts.com",
    category: "Personal",
  },
  {
    name: "buttondown.com/hillelwayne",
    xmlUrl: "https://buttondown.com/hillelwayne/rss",
    htmlUrl: "https://buttondown.com/hillelwayne",
    category: "Engineering",
  },
  {
    name: "dwarkesh.com",
    xmlUrl: "https://www.dwarkeshpatel.com/feed",
    htmlUrl: "https://dwarkesh.com",
    category: "Culture",
  },
  {
    name: "borretti.me",
    xmlUrl: "https://borretti.me/feed.xml",
    htmlUrl: "https://borretti.me",
    category: "Engineering",
  },
  {
    name: "wheresyoured.at",
    xmlUrl: "https://www.wheresyoured.at/rss/",
    htmlUrl: "https://wheresyoured.at",
    category: "Culture",
  },
  {
    name: "jayd.ml",
    xmlUrl: "https://jayd.ml/feed.xml",
    htmlUrl: "https://jayd.ml",
    category: "Personal",
  },
  {
    name: "minimaxir.com",
    xmlUrl: "https://minimaxir.com/index.xml",
    htmlUrl: "https://minimaxir.com",
    category: "AI",
  },
  {
    name: "geohot.github.io",
    xmlUrl: "https://geohot.github.io/blog/feed.xml",
    htmlUrl: "https://geohot.github.io",
    category: "Engineering",
  },
  {
    name: "paulgraham.com",
    xmlUrl: "http://www.aaronsw.com/2002/feeds/pgessays.rss",
    htmlUrl: "https://paulgraham.com",
    category: "Tech",
  },
  {
    name: "filfre.net",
    xmlUrl: "https://www.filfre.net/feed/",
    htmlUrl: "https://filfre.net",
    category: "Culture",
  },
  {
    name: "blog.pixelmelt.dev",
    xmlUrl: "https://blog.pixelmelt.dev/rss/",
    htmlUrl: "https://blog.pixelmelt.dev",
    category: "Engineering",
  },
  {
    name: "dfarq.homeip.net",
    xmlUrl: "https://dfarq.homeip.net/feed/",
    htmlUrl: "https://dfarq.homeip.net",
    category: "Personal",
  },
  {
    name: "jyn.dev",
    xmlUrl: "https://jyn.dev/atom.xml",
    htmlUrl: "https://jyn.dev",
    category: "Engineering",
  },
  {
    name: "martinalderson.com",
    xmlUrl: "https://martinalderson.com/feed.xml",
    htmlUrl: "https://martinalderson.com",
    category: "Engineering",
  },
  {
    name: "danielchasehooper.com",
    xmlUrl: "https://danielchasehooper.com/feed.xml",
    htmlUrl: "https://danielchasehooper.com",
    category: "Engineering",
  },
  {
    name: "chiark.greenend.org.uk/~sgtatham",
    xmlUrl: "https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/feed.xml",
    htmlUrl: "https://chiark.greenend.org.uk/~sgtatham",
    category: "Engineering",
  },
  {
    name: "grantslatton.com",
    xmlUrl: "https://grantslatton.com/rss.xml",
    htmlUrl: "https://grantslatton.com",
    category: "Engineering",
  },
  {
    name: "experimental-history.com",
    xmlUrl: "https://www.experimental-history.com/feed",
    htmlUrl: "https://experimental-history.com",
    category: "Science",
  },
  {
    name: "anildash.com",
    xmlUrl: "https://anildash.com/feed.xml",
    htmlUrl: "https://anildash.com",
    category: "Tech",
  },
  {
    name: "aresluna.org",
    xmlUrl: "https://aresluna.org/main.rss",
    htmlUrl: "https://aresluna.org",
    category: "Personal",
  },
  {
    name: "michael.stapelberg.ch",
    xmlUrl: "https://michael.stapelberg.ch/feed.xml",
    htmlUrl: "https://michael.stapelberg.ch",
    category: "Engineering",
  },
  {
    name: "miguelgrinberg.com",
    xmlUrl: "https://blog.miguelgrinberg.com/feed",
    htmlUrl: "https://miguelgrinberg.com",
    category: "Engineering",
  },
  {
    name: "keygen.sh",
    xmlUrl: "https://keygen.sh/blog/feed.xml",
    htmlUrl: "https://keygen.sh",
    category: "Engineering",
  },
  {
    name: "mjg59.dreamwidth.org",
    xmlUrl: "https://mjg59.dreamwidth.org/data/rss",
    htmlUrl: "https://mjg59.dreamwidth.org",
    category: "Security",
  },
  {
    name: "computer.rip",
    xmlUrl: "https://computer.rip/rss.xml",
    htmlUrl: "https://computer.rip",
    category: "Engineering",
  },
  {
    name: "tedunangst.com",
    xmlUrl: "https://www.tedunangst.com/flak/rss",
    htmlUrl: "https://tedunangst.com",
    category: "Engineering",
  },
  {
    name: "Medium - AI",
    xmlUrl: "https://medium.com/feed/tag/ai",
    htmlUrl: "https://medium.com",
    category: "AI",
  },
  {
    name: "Medium - Tech",
    xmlUrl: "https://medium.com/feed/tag/tech",
    htmlUrl: "https://medium.com",
    category: "Tech",
  },
  {
    name: "Medium - AI Tools",
    xmlUrl: "https://medium.com/feed/tag/ai-tools",
    htmlUrl: "https://medium.com",
    category: "AI",
  },
  {
    name: "TLDR Tech",
    xmlUrl: "https://tldr.tech/api/rss/tech",
    htmlUrl: "https://tldr.tech",
    category: "Tech",
  },
];
